# Generated by Django 2.0.4 on 2018-06-30 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReservation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dateofreservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencenumber', models.CharField(default='UNREF', max_length=5)),
                ('noofguest', models.IntegerField()),
                ('dateofactualvisit', models.DateField()),
                ('timeofarrival', models.TimeField()),
                ('timeofdeparture', models.TimeField()),
                ('cottagenumber', models.IntegerField()),
                ('modeofbooking', models.CharField(choices=[('PV', 'Personal Visit'), ('LL', 'Landline'), ('MP', 'Mobile Phone'), ('WWW', 'Internet')], max_length=3)),
                ('typeofreservation', models.CharField(choices=[('R', 'Regular'), ('E', 'Excursion')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Cancelled'), ('D', 'Declined'), ('P', 'Pending')], default='P', max_length=1)),
                ('remarks', models.TextField()),
                ('isdeleted', models.BooleanField(default=False)),
                ('turn', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.Profile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.Profile')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical reservation',
            },
        ),
        migrations.CreateModel(
            name='MaxNumberOfGuestSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxnumberofguest', models.IntegerField(default=400)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofreservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencenumber', models.CharField(default='UNREF', max_length=5)),
                ('noofguest', models.IntegerField()),
                ('dateofactualvisit', models.DateField()),
                ('timeofarrival', models.TimeField()),
                ('timeofdeparture', models.TimeField()),
                ('cottagenumber', models.IntegerField()),
                ('modeofbooking', models.CharField(choices=[('PV', 'Personal Visit'), ('LL', 'Landline'), ('MP', 'Mobile Phone'), ('WWW', 'Internet')], max_length=3)),
                ('typeofreservation', models.CharField(choices=[('R', 'Regular'), ('E', 'Excursion')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Cancelled'), ('D', 'Declined'), ('P', 'Pending')], default='P', max_length=1)),
                ('remarks', models.TextField()),
                ('isdeleted', models.BooleanField(default=False)),
                ('turn', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='people.Profile')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='people.Profile')),
            ],
        ),
    ]
