# Generated by Django 2.0.4 on 2018-09-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180917_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreservation',
            name='typeofreservation',
            field=models.CharField(blank=True, choices=[('R', 'Regular'), ('E', 'Excursion')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='typeofreservation',
            field=models.CharField(blank=True, choices=[('R', 'Regular'), ('E', 'Excursion')], max_length=1, null=True),
        ),
    ]
